apiVersion: v1
kind: Service
metadata:
  name: {{ include "entity-extractor-service.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    {{- include "entity-extractor-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "entity-extractor-service.selectorLabels" . | nindent 4 }}
